// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { existsSync } from 'fs';
import { resolve } from 'path';
import { defineConfig, env } from 'prisma/config';

// 프로젝트 루트의 .env 파일 로드
// 우선순위:
// 1. Docker 컨테이너 내: /app/.env
// 2. 로컬 개발 (프로젝트 루트): ../.env (prisma.config.ts는 server 폴더에 있음)
// 3. 현재 작업 디렉토리: .env
const possiblePaths = [
  '/app/.env', // Docker 컨테이너 내부
  resolve(__dirname, '../.env'), // server 폴더에서 프로젝트 루트
  resolve(process.cwd(), '.env'), // 현재 작업 디렉토리
];

let envLoaded = false;
for (const envPath of possiblePaths) {
  if (existsSync(envPath)) {
    config({ path: envPath });
    envLoaded = true;
    break;
  }
}

// 파일을 찾지 못한 경우 기본 dotenv 동작
if (!envLoaded) {
  config();
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
